# ===========================================
# Site Settings
# ===========================================
# Header
site_title: Gr00t的安全工厂
site_description: I Am Gr00t，不定期更新原创或转载一些安全相关文章，内容包括代码审计、1day分析、漏洞推送、红队工具、学习成果等，欢迎关注、点赞、转发、投稿、吹水!
# ---Optional ---
site_avatar: /images/avatar.png
artical_license_statement: 本文由https://mrgr00t.github.io原创编写，转载请尽量保留版权网址，感谢您的理解与分享!
# ---End Optional ---
menu:
  Home: /
  Archives: /archives
#  AboutMe: /about

# display widgets
widgets:
- archives
#- search
#- social_links
- recent_posts
- tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon:

# ===========================================
# Miscellaneous Settings
# ===========================================
# Baidu Analytics
baidu_analytics: 542b4962c3c4035fce9071b7c665f0d2
# Google Analytics
google_analytics: UA-97838175-1
# addthis_analytics: ra-5d3d630390ef40ae
# Disqus
disqus:
  enable: false
  shortname: troyyang-com
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: false
  shortname: troyyang
# Visitors
leancloud_visitors:
  enable: false
  app_id: wzqncxgqp9MCPiPERe3gnX2Q-gzGzoHsz
  app_key: CCtBiqyPtJWupuozt1393AXm
  server_url: https://wzqncxgq.lc-cn-n1-shared.com
donation:
  enable: false
  alipay: /images/alipay-qr.png
  wechat: /images/wechat-qr.png

# Search 
# Note: please install hexo-generator-search plugin and config the root _config.yml (not theme's _config.yml) as below value search.json(https://www.npmjs.com/package/hexo-generator-search):
#search:
#  path: search.json
#  field: post
infinite:
  enable: false
  title1: Happy Coding, Happy Life!
  title2: 蜀ICP备15004900号-2
